---
title: "About"
description: |
  My name is Grace and I AM THE BEST! HAHAHA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Grace Kumaishi graduated from the University of California, Los Angeles in 2017 with a Bachelor of Science in Ecology, Behavior, and Evolution. Growing up in Santa Cruz, California, Grace always felt a deep connection to the ocean and surrounding coastal ecosystems. This love was intensified through her undergraduate career, during which she participated in two field biology courses in Australia and Southern California. Upon graduating from UCLA, Grace began working for Point Blue Conservation Science in Northern California, studying marine predator diet. She joined four at-sea research cruises in partnership with NOAA and local National Marine Sanctuaries and learned the tumultuous art of working at sea. Following her position in the marine lab, Grace continued to work for Point Blue, studying breeding seabirds on Southeast Farallon Island. While dodging furious Western Gulls and extracting tiny Pigeon Guillemot chicks from rocky crevices, Grace’s passion for marine conservation grew. She is excited to further her education at the Bren School, where she hopes to explore the dynamics between human populations and their neighboring marine ecosystems. Grace intends to specialize in Conservation Planning and Coastal Marine Resources Management, and looks forward to gaining exposure to various career paths in the field.   
