---
title: "Static and interactive maps"
description: |
  exploring oil spill incidents in California 
author:
  - name: Grace Kumaishi
date: 02-17-2021
output:
  distill::distill_article:
    self_contained: false
    code_folding: Code
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(here)
library(sf)
library(janitor)
library(tmap)
```

```{r}
# Read in the data:
oil_spill <- read_sf(here("data", "oil_spill", "Oil_Spill_Incident_Tracking_%5Bds394%5D.shp")) %>%
  clean_names()

ca_counties <- read_sf(here("data", "ca_counties", "CA_Counties_TIGER2016.shp"))

ca_subset <- ca_counties %>% 
  select(NAME, ALAND) %>% 
  rename(county_name = NAME, land_area = ALAND)

# Check CRS:
# ca_counties %>% st_crs()
# oil_spill %>%  st_crs()
```

### 1) Interactive map
```{r}
# Set the viewing mode to interactive:
tmap_mode(mode = "view")

# Make the map:
tm_shape(ca_subset) +
  tm_borders() +
  tm_shape(oil_spill) +
  tm_dots(col = "royalblue4")
```

**Map 1:** Individual oil spill events in California. (Data: CA DFW Oil Spill Incident Tracking).

### 2) Static choropleth map
```{r}
# Join!
inland_spill_county <- ca_subset %>% 
  st_join(oil_spill)

inland_spill_counts <- inland_spill_county %>% 
  count(localecoun)

ggplot(data = inland_spill_counts) +
  geom_sf(aes(fill = n), color = "white", size = 0.1) +
  scale_fill_gradientn(colors = c("lightgray", "royalblue1", "royalblue4")) +
  theme_minimal() +
  labs(fill = "Number of inland oil spills",
       x = "Latitude",
       y = "Longitude")
```

**Map 2:** Choropleth map showing oil spill events per county in California. Darker counties indicate those with a greater number of incidents. (Data: CA DFW Oil Spill Incident Tracking).

### Citation:
[Oil Spill layers courtesty of CA DFW Oil Spill Incident Tracking [ds394]. Edition 2008. Published 2009-07-23.](https://map.dfg.ca.gov/metadata/ds0394.html) 

[California county layers courtesy of California Department of Technologies. CA Geographic Boundaries. US Census Bureau's 2016 MAF/TIGER database.](https://data.ca.gov/dataset/ca-geographic-boundaries)